### ISSUE TITLE
JM_imp(); example for unbalanced longitudinal multinomial logit models

### ISSUE THREAD

**Issue by Erfanit64** [NErler/JointAI#1]
Hi,

I came across your project and find JM_imp() function that was explained as "joint model for longitudinal and survival data". However, I couldn't execute it on a unbalanced panel data with dependent variable being a 3 categories outcome variable. I appreciate it if you could demonstrate JM_imp() on a similar example (unbalanced longitudinal multinomial logit model).

Thanks.
Erfan

**Comment by NErler** [comment]
The `JM_imp()` function fits joint models for longitudinal (panel) and time-to-event data, however, it can currently not yet handle multinomial longitudinal variables. If your setting does not involve a time-to-event outcome you probably should use `mlogitmm()` instead.
What exactly is your setting?

**Comment by Erfanit64** [comment]
Thank you for your reply. The data is monthly agent-level observations to study peer influence on agents' decision outcome (for example four unordered/categorical outcomes "outcome1", "outcome2", "outcome3", "outcome4" ) that happens every month periodically which I think it is different from time-to-event analysis. The data is unbalanced since agents' data are not available for all the months in the panel, due to their start and ending dates of employment. The **longitudinal** form of the model for non-binary dependent variable would be as follows: 

**MODLE**: **Y**(it)= **alpha** + **a**(it)**Y**(it-1) + **b**(it)**X**(it) + **c**(it)**Gx**(it,outcome_n) + **d**(it)**Gy**(it,outcome_n) + **f**(t) + e(it)

where,

**Y(it)**: is agent i's decision outcome at time t (multinomial variable, more than two outcomes)

**Y(it-1)**: is agent i's previous decision outcome (Granger causality)

**X(it)**: is agent-specific exogenous or contextual variable at time t (this variable is continuous but can be binary or categorical too)

**Gx(it,outcome_n)**: is a decision-specific variable and equals to variable **X**'s average of peers who have the same decision as agent i in **Y(it)** [for example if agent i's decision at time t is "outcome2", we use members from the reference group that have same "outcome2" decision] and calculated by (**sum of X of peers with the same decision as in Y(it)**)**/**(**agent i's group size at time t**)

**Gy(it,outcome_n)**: is a decision-specific variable and equals to the average of decisions that are same as what we observed in Y(it) and calculated by (**number of similar outcomes in the agent i's reference group at time t**)**/**(**agent i's group size at time t**)


Assuming that we are allowed to ignore identification issues, do you think that **`mlogitmm()`** is still the right function to estimate the following parameters:

**alpha**: constant factor
**a**: coefficient for Granger causality
**b**: coefficient vector for the agent's exogenous variable (X)
**c**: coefficient vector for the group's average contextual variable (Gx)
**d**: coefficient for group's decision effect (Gy)
**f**: time (or month) fixed effect

**Comment by Erfanit64** [comment]
Link to sample data: [https://docs.google.com/spreadsheets/d/1_3J57HlDJeX2TIieAfY0Ku6qL_FxojWCotYBZq2lrAY/edit?usp=sharing](url)
