### ISSUE TITLE
current value+slope value in JointAI package?

### ISSUE THREAD

**Issue by amirabadiza921** [NErler/JointAI#11]
Hi,
Thank you very much for such great and interesting package!
Can we have the current value+slope  from the JointAI package like the JMbayes2 package?
Thanks

**Comment by NErler** [comment]
Hi,
Thank you for your kind feedback.
Having the option to use a slope association structure would indeed be a great addition. Unfortunately, it's difficult for me to find the time on working on such larger extensions at the moment. A slope association is on my to-do list but I can't indicate when I will get around to it.
