### ISSUE TITLE
Get imputation values for survival model

### ISSUE THREAD

**Issue by bbb801** [NErler/JointAI#3]
Dear Sir or Madam
I am running the guideline survival models and would like to extract the imputed data. I got a error. Any suggestion? Thanks.
> library(JointAI)
> mod6a <- survreg_imp(Surv(futime, status != "alive") ~ age + sex +
                         copper + trig, models = c(copper = "lognorm", trig = "lognorm"),
                      data = subset(PBC, day == 0), n.iter = 250,monitor_params = c(analysis_main=TRUE, imp=TRUE))
  |**************************************************| 100%
Warning message:
In readChar(modelfile, file.info(modelfile)$size) :
  can only read in bytes in a non-UTF-8 MBCS locale
> impDF <- get_MIdat(mod6a, m = 10, seed = 2019)
Error: 
I cannot find imputed values for “copper”. Did you monitor them?
> mod6b <- coxph_imp(Surv(futime, status != "alive") ~ age + sex +
                       copper + trig,# models = c(copper = "lognorm", trig = "lognorm"),
                   data = subset(PBC, day == 0), n.iter = 250,monitor_params = c(analysis_main=TRUE, imp=TRUE))
  |**************************************************| 100%
Warning message:
In readChar(modelfile, file.info(modelfile)$size) :
  can only read in bytes in a non-UTF-8 MBCS locale
> impDF <- get_MIdat(mod6b, m = 10, seed = 2019)
Error: 
I cannot find imputed values for “copper”. Did you monitor them?

![image](https://user-images.githubusercontent.com/52306405/153923762-c6d60856-5ac7-42ef-b6e1-72a715d5f5fc.png)

**Comment by NErler** [comment]
Thank you for your post. This is indeed a bug. The wrong elements of the data matrix are set to be monitored. I will look into fixing this. In the meantime, you can "solve" the issue by specifying the correct elements to be monitored via the "other" argument of `monitor_params`.

```r
library("JointAI")

# modelspecification without actually running it
mod0 <- survreg_imp(Surv(futime, status != "alive") ~ age + sex +
                       copper + trig, models = c(copper = "lognorm", trig = "lognorm"),
                     data = subset(PBC, day == 0), n.adapt = 0)

# indices of the column and rows of the data matrix containing the variable "copper"
col <- which(colnames(mod0$data_list$M_lvlone) == "copper")
rows <- which(is.na(mod0$data_list$M_lvlone[, "copper"]))

# node to be monitored
imp_copper <- paste0("M_lvlone[", rows, ",", col, "]")

# run the model
mod6a <- update(mod0, n.adapt = 100, n.iter = 250,
                monitor_params = list(imps = TRUE, other = imp_copper))

# extract the imputed values
impDF <- get_MIdat(mod6a, m = 10, seed = 2019)
```

**Comment by bbb801** [comment]
Thank you! Dr NErler.

**Comment by NErler** [comment]
It is not yet possible to fit competing risk models in JointAI.
There is no out-of-the-box solution for imputing values in another dataset using the parameter estimates from the first dataset. 
Missing values in covariates are imputed from their full-conditional posterior distributions, which are derived within JAGS from the joint distribution that JointAI specifies.
Imputing values in a new dataset based on the parameters from the original data would require you to do this sampling in R, using, for instance, a Metropolis-Hastings sampler because the imputation models will usually not have a closed-form.
