### ISSUE TITLE
It is currently not possible to use “contr.poly” for incomplete categorical covariates. I will use “contr.treatment” instead.  You can specify (globally) which types of contrasts are used by changing “options('contrasts')”.

### ISSUE THREAD

**Issue by bbb801** [NErler/JointAI#4]
Dear Dr Nicole Erler

My whole data has over 30,0000 and 884 columns. Now I just sample 1000 rows for testing using using 'survreg_imp' function. Then it has been running for a whole day and never stops, just with 1000 rows data; I also see the warning:
Warning: 
It is currently not possible to use “contr.poly” for incomplete categorical covariates. I will use “contr.treatment” instead.  You can specify (globally) which types of contrasts are used by changing “options('contrasts')”.

Here shows the codes:
> d<-d[sample(nrow(d), 1000), ]
> f<-as.formula(paste('Surv(survival_time,', i,')~',paste(names(d)[!names(d) %in% label_used],collapse='+'))) 
> mod1 <- survreg_imp(f,data = d[!names(d) %in% label_used], n.iter = 250,shrinkage = 'ridge',seed=1,monitor_params = c(analysis_main=TRUE,other_models = TRUE, imps = TRUE)) 
![image](https://user-images.githubusercontent.com/52306405/154524253-f023dafa-ea25-4ff6-b64e-622d7ff31727.png)

Could you provide some suggestions?

**Comment by NErler** [comment]
How many covariates do you have in the model and how many are incomplete?
