### ISSUE TITLE
Does JM_imp() have different functional_forms?

### ISSUE THREAD

**Issue by mikoSL** [NErler/JointAI#5]
Hi, 
Thank you very much for such great and interesting package! 

I have one question, does JM_imp have different functional forms, which are similar with JMBayes2 package?
[different functional forms in JMBayes2](https://drizopoulos.github.io/JMbayes2/articles/Transformation_Functions.html)

Thank you for your time and look forward to hearing more about it. :)

**Comment by NErler** [comment]
Currently, you can only choose between using the underlying value or the observed/imputed value (via the argument `assoc_type`. The slope or a cumulative effect is not yet implemented.

**Comment by waybo-zz** [comment]
Could we get the slope or a cumulative effect in the following way?
(1) run the JM_imp and then get the Imputed data by get_MIdat function
(2) Run the Imputed data in JMBayes2 package

Thanks.
