### ISSUE TITLE
JM_imp() for binary longitudinal data and right-censored multistate survival data

### ISSUE THREAD

**Issue by axinaxia** [NErler/JointAI#6]
Dear Dr. Nicole Erler,

I am trying to understand if I can use JM_imp() for my study, which investigates the relationship between a time-varying binary variable (exposure) and right-censored survival outcomes with missing values in the binary variable.

I didn't find an example for binary/categorical time-varying covariates and survival data in this paper https://www.jstatsoft.org/article/view/v100i20. Is it possible to do? In addition, is it possible to use JM_imp() for multistate data as JMbayes2 does?

Thanks a lot!

Xin

**Comment by NErler** [comment]
Dear Xin,
You can use JM_imp() with a binary time-varying variable and right censored time-to-event outcome.
The specification is the same as for a continuous longitudinal variable. The type of mixed model that is used for the longitudinal variable is determined based on how the variable is coded, i.e., for a factor with 2 levels a logistic mixed model is chosen. You can change that by using the `models` argument of JM_imp().
Note that the default association structure for categorical longitudinal variables is to use the observed/imputed value and not the underlying value. This can be changed by setting the `assoc_type` argument (i.e., `assoc_type = c(<variable name> = "underl.value")`).

It is not (yet) possible to use multi-state models.

Best,
Nicole
