### ISSUE TITLE
Error in is.nan(data[, k]) :    default method not implemented for type 'list'

### ISSUE THREAD

**Issue by amirabadiza921** [NErler/JointAI#8]
Dear Dr. Erler,
I get this error when running the following commands:
model.cox<-coxph_imp(Surv(surv_time,incidenceDM)~BMI_1+ageyr14_1+tg1_1+sbp_1+dbp_1+
+ hdl1_1+chol1_1+ifcvd1_1,
+ data=data,x=T,model=TRUE,n.iter=200)
Error in is.nan(data[, k]) : 
  default method not implemented for type 'list'
> fit.lm1<-lme_imp(log(TSH_)~time ,random= ~time | code,data=dataLong,n.iter=200)
Error in is.nan(data[, k]) : 
  default method not implemented for type 'list'
Many thank you for your guidance,
Alireza

**Comment by NErler** [comment]
Dear Alireza,

Could you provide a reproducible example? It might have to do with the particular coding of your data, but I am not able to figure it out without an example that I can run myself to re-create the problem.

Thank you.
